// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Models;

namespace Server.Migrations
{
    [DbContext(typeof(MoviesDB))]
    [Migration("20201023033732_MoviesMigration")]
    partial class MoviesMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Server.Models.Movie", b =>
                {
                    b.Property<int>("IdMovie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Director")
                        .HasColumnName("Director")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(true);

                    b.Property<int>("Genre")
                        .HasColumnName("Genre")
                        .HasColumnType("int");

                    b.Property<byte?>("IMDB")
                        .HasColumnName("IMDB")
                        .HasColumnType("tinyint");

                    b.Property<string>("ImageId")
                        .HasColumnName("ImageId")
                        .HasColumnType("nvarchar(max)")
                        .IsUnicode(true);

                    b.Property<bool>("IsFavorite")
                        .HasColumnName("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<int>("Language")
                        .HasColumnName("Language")
                        .HasColumnType("int");

                    b.Property<byte?>("MetaScore")
                        .HasColumnName("MetaScore")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(true);

                    b.Property<byte>("Popularity")
                        .HasColumnName("Popurarity")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Qualification")
                        .HasColumnName("Qualification")
                        .HasColumnType("tinyint");

                    b.Property<int>("Style")
                        .HasColumnName("Style")
                        .HasColumnType("int");

                    b.Property<DateTime>("Year")
                        .HasColumnName("Year")
                        .HasColumnType("date");

                    b.HasKey("IdMovie")
                        .HasName("PRIMARY");

                    b.ToTable("Movie");
                });
#pragma warning restore 612, 618
        }
    }
}
